- hosts: all
  become: yes
  tasks:
    - name: Install apache2
      apt: name=apache2 state=present update_cache=yes

    - name: Add index.html
      shell: curl http://169.254.169.254/latest/meta-data/instance-id/ >> /var/www/html/id.html
